name: Build

on:
  push:
    branches-ignore: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Run Fake
      run: ./build.sh -t BuildAction
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
        OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
        OP_CONNECT_ADDITIONAL_HEADERS: ${{ secrets.OP_CONNECT_ADDITIONAL_HEADERS }}
        SLEET_FEED_TYPE: 'op://GitHub/eowr7yml3nrvy3iobdcil5z6r4/type'
        SLEET_FEED_BASEURI: 'op://GitHub/eowr7yml3nrvy3iobdcil5z6r4/baseURI'
        SLEET_FEED_CONTAINER: 'op://GitHub/eowr7yml3nrvy3iobdcil5z6r4/container'
        SLEET_FEED_CONNECTIONSTRING: 'op://GitHub/eowr7yml3nrvy3iobdcil5z6r4/connectionString'
